apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/

    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: trivycache
          mountPath: /tmp/trivycache/
      # ⚠️ removed docker socket mount

    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true

    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true

  volumes:
    - name: m2
      emptyDir: {}

    - name: trivycache
      emptyDir: {}

    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
